repos:
-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: python3 -m unittest discover -v
        language: python
        types: [python]
        additional_dependencies: [sqlalchemy, geoalchemy2, pytimeparse, omegaconf, hydra, parsedatetime]
        pass_filenames: false
        stages: [push] #can be commented to test pre-commit