-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: python3 -m unittest discover
        language: python
        'types': [python]
        pass_filenames: false
        stages: [push]