TemplateCoreLib:
  env:
    MEMCACHED_HOST: localhost
    MEMCACHED_PORT: 11211
  config:
    data:
      user_db:
        log_queries: false
        create_db: true
        session:
          pool_recycle: 3200
          pool_pre_ping: false
        url:
          protocol: sqlite
    cache:
      type: memcached
      host: ${oc.env:MEMCACHED_HOST}
      port: ${oc.env:MEMCACHED_PORT}
    jobs:
      my_job:
        initial_delay: 0s
        frequency: ''
        handler:
          _target_: core_lib.jobs.UpdateUser
  data_layers:
    data:
      User:
        name: User
        db_connection: user_db
        columns:
          username:
            name: username
            type: VARCHAR
            default: ''
          password:
            name: password
            type: VARCHAR
            default: ''
        is_soft_delete: true
        is_soft_delete_token: false
      Customer:
        name: Customer
        db_connection: user_db
        columns:
          name:
            name: name
            type: VARCHAR
            default: ''
          password:
            name: password
            type: VARCHAR
            default: ''
          contact:
            name: contact
            type: INTEGER
            default: 0
        is_soft_delete: true
        is_soft_delete_token: true
      migrate: true
    data_access:
      UserDataAccess:
        name: UserDataAccess
        entity: User
        is_crud: true
        is_crud_soft_delete: true
        db_connection: user_db
      CustomerDataAccess:
        name: CustomerDataAccess
        entity: Customer
        db_connection: user_db
