core_lib:
  app:
    secret: 000000000000000000101010110

  db:
    log_queries: false
    create_db: true
    session:
      pool_recycle: 3600
      pool_pre_ping: false
    url:
      protocol: sqlite

  solr:
    protocol: http
    host: localhost
    port: 8983
    file: solr/test

  memcached:
    host: localhost
    port: 11211