core_lib:
  facebook_core_lib:
    data:
      userdb:
        log_queries: false
        create_db: true
        session:
          pool_recycle: 3200
          pool_pre_ping: false
        url:
          protocol: postgresql
          username: ${oc.env:USERDB_USER}
          password: ${oc.env:USERDB_PASSWORD}
          host: ${oc.env:USERDB_HOST}
          port: ${oc.env:USERDB_PORT}
          file: ${oc.env:USERDB_DB}
      sellerdb:
        log_queries: false
        create_db: true
        session:
          pool_recycle: 3200
          pool_pre_ping: false
        url:
          protocol: postgresql
          username: ${oc.env:SELLERDB_USER}
          password: ${oc.env:SELLERDB_PASSWORD}
          host: ${oc.env:SELLERDB_HOST}
          port: ${oc.env:SELLERDB_PORT}
          file: ${oc.env:SELLERDB_DB}
    cache:
      type: memcached
      url:
        host: ${oc.env:MEMCACHED_HOST}
        port: ${oc.env:MEMCACHED_PORT}
    jobs:
      my_job:
        initial_delay: 0s
        frequency: ''
        handler:
          _target_: facebook_core_lib.core_lib.jobs.my_job.UpdateSeller
